"""Import xiaoheihe crawled data into the database."""
import sys
import os
# Add project root to path
project_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, project_root)

from backend.db.database import init_db
from backend.ingestion.importer import import_from_dict

# Initialize database
init_db()

# Collected data from xiaoheihe browser crawling
records = [
    # === 原神 posts ===
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "原神",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "LDoven",
        "author_id": "86515913",
        "followers": 0,
        "content": "0.01给我碰上了？？😨",
        "title": "0.01给我碰上了？？😨",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/173682397",
        "publish_time": "2025-01-17",
        "likes": 703,
        "comments": 1490,
        "shares": 0,
        "tags": "原神",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "原神",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "人在初灯夜未央",
        "author_id": "5626998",
        "followers": 0,
        "content": "起猛了地铁上看到王小美了",
        "title": "起猛了地铁上看到王小美了",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/155042323",
        "publish_time": "2025-05-23",
        "likes": 148,
        "comments": 835,
        "shares": 0,
        "tags": "原神",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "原神",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "玩家93386221",
        "author_id": "93386221",
        "followers": 0,
        "content": "这武器能给菲林斯用吗",
        "title": "这武器能给菲林斯用吗",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/189594389",
        "publish_time": "2025-09-02",
        "likes": 29,
        "comments": 6,
        "shares": 0,
        "tags": "原神",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "原神",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "萌主彤",
        "author_id": "96033062",
        "followers": 0,
        "content": "有人带我补探索嘛求带带",
        "title": "有人带我补探索嘛求带带",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/189809248",
        "publish_time": "2025-09-03",
        "likes": 12,
        "comments": 1,
        "shares": 0,
        "tags": "原神",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "原神",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "纱雾的雾",
        "author_id": "44129080",
        "followers": 0,
        "content": "感谢原神 朋友玩原神前和玩原神后",
        "title": "感谢原神 朋友玩原神前和玩原神后",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/188399145",
        "publish_time": "2025-08-18",
        "likes": 15,
        "comments": 10,
        "shares": 0,
        "tags": "原神",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "原神",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "玩家55090578",
        "author_id": "55090578",
        "followers": 0,
        "content": "好看捏 不靠自己全靠母亲直接拿下",
        "title": "好看捏",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/186879293",
        "publish_time": "2025-07-29",
        "likes": 40,
        "comments": 305,
        "shares": 0,
        "tags": "原神",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "原神",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "云饼饼",
        "author_id": "103740833",
        "followers": 0,
        "content": "不想玩了，退游了，这个号便宜出可以卖多少摩拉。",
        "title": "不想玩了，退游了",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/189735258",
        "publish_time": "2025-09-03",
        "likes": 9,
        "comments": 1,
        "shares": 0,
        "tags": "原神",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "原神",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "玩家192255",
        "author_id": "19216255",
        "followers": 0,
        "content": "100r接了个至冬全包，力竭了，第一次接不知道这个价格是黑奴价，魔神任务和6个开图主线都要打一天，然后才开始满探索，打了三天终于打完了，号主的练度也不太高(就两个90级)，被至冬传奇老头(被摸一下原地飞升了)折磨了一个半小时真是草了。",
        "title": "100r接了个至冬全包，力竭了",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/189585660",
        "publish_time": "2025-09-01",
        "likes": 498,
        "comments": 102,
        "shares": 0,
        "tags": "原神,至冬",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "原神",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "yxgsxpg",
        "author_id": "72088781",
        "followers": 0,
        "content": "买了一个原神亚服号，花了2400亏了吗",
        "title": "买了一个原神亚服号，花了2400亏了吗",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/189730016",
        "publish_time": "2025-09-03",
        "likes": 8,
        "comments": 2,
        "shares": 0,
        "tags": "原神",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "原神",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "永夜不载星河",
        "author_id": "30496592",
        "followers": 0,
        "content": "我终于有满命五星了，啊啊啊啊",
        "title": "我终于有满命五星了，啊啊啊啊",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/189573242",
        "publish_time": "2025-09-01",
        "likes": 14,
        "comments": 11,
        "shares": 0,
        "tags": "原神",
    },
    # === 崩坏：星穹铁道 posts ===
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "崩坏：星穹铁道",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "临雲海",
        "author_id": "0",
        "followers": 0,
        "content": "崩铁终于出官方查看跃迁记录了。虽然不是很明白为什么之前一直不出，毕竟是玩家呼吁了很久的功能，或许是怕出了会导致社区更加混乱，玩家更加敏感，毕竟比起自身的不幸，他人的好运或许会是痛苦更加有力的来源。之前也一直对自己的抽卡情况感受挺模糊的，只觉得自己绝对不算非的人，非官方途径查询也用过，但是每次都得很多操作后来就放弃了，今天直观看了下，感觉还是挺有意思的，角色虽然一直接近保底出但挺久没歪过了，光锥虽然歪的多一些，但是经常狗运提前出。",
        "title": "崩铁终于出官方查看跃迁记录了",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/189115514",
        "publish_time": "2025-08-26",
        "likes": 110,
        "comments": 34,
        "shares": 0,
        "tags": "崩坏：星穹铁道,抽卡分析",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "崩坏：星穹铁道",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "Iwer",
        "author_id": "0",
        "followers": 0,
        "content": "女友视角(？)拍完才发现发箍掉下来了，头太大了经常会撑下来",
        "title": "女友视角拍完才发现发箍掉下来了",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/183412170",
        "publish_time": "2025-06-14",
        "likes": 263,
        "comments": 4230,
        "shares": 0,
        "tags": "崩坏：星穹铁道",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "崩坏：星穹铁道",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "死灵游侠",
        "author_id": "0",
        "followers": 0,
        "content": "为什么米哈游至今做不出退出游戏？是非常难的技术吗？",
        "title": "为什么米哈游至今做不出退出游戏？",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/188514618",
        "publish_time": "2025-08-19",
        "likes": 2155,
        "comments": 344,
        "shares": 0,
        "tags": "原神,崩坏：星穹铁道",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "崩坏：星穹铁道",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "笙夏",
        "author_id": "0",
        "followers": 0,
        "content": "有人知道这是为啥吗，崩铁突然给我转了 10 块钱",
        "title": "崩铁突然给我转了 10 块钱",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/182787929",
        "publish_time": "2025-06-05",
        "likes": 22,
        "comments": 28,
        "shares": 0,
        "tags": "崩坏：星穹铁道",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "崩坏：星穹铁道",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "冰希凌",
        "author_id": "0",
        "followers": 0,
        "content": "王琪自动进不了0t这正常吗，感觉玩的怪怪的，有大佬帮我看一下嘛",
        "title": "王琪自动进不了0t这正常吗",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/189684368",
        "publish_time": "2025-09-02",
        "likes": 9,
        "comments": 2,
        "shares": 0,
        "tags": "崩坏：星穹铁道",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "崩坏：星穹铁道",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "亡灵的大镰刀",
        "author_id": "0",
        "followers": 0,
        "content": "我觉得崩铁最涩的角色有共同爱好吗",
        "title": "我觉得崩铁最涩的角色",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/170202388",
        "publish_time": "2025-12-07",
        "likes": 207,
        "comments": 654,
        "shares": 0,
        "tags": "崩坏：星穹铁道",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "崩坏：星穹铁道",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "玩家103345635",
        "author_id": "103345635",
        "followers": 0,
        "content": "屯屯鼠究极大胜利✌舒服了",
        "title": "屯屯鼠究极大胜利",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/189702779",
        "publish_time": "2025-09-03",
        "likes": 1,
        "comments": 1,
        "shares": 0,
        "tags": "崩坏：星穹铁道",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "崩坏：星穹铁道",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "松灯0",
        "author_id": "0",
        "followers": 0,
        "content": "我哪里来跳跃键",
        "title": "我哪里来跳跃键",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/186712637",
        "publish_time": "2025-07-27",
        "likes": 29,
        "comments": 115,
        "shares": 0,
        "tags": "崩坏：星穹铁道",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "崩坏：星穹铁道",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "清风丨挽袖",
        "author_id": "0",
        "followers": 0,
        "content": "崩铁单独上市了？",
        "title": "崩铁单独上市了？",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/189481992",
        "publish_time": "2025-08-31",
        "likes": 113,
        "comments": 40,
        "shares": 0,
        "tags": "崩坏：星穹铁道",
    },
    # === 绝区零 posts ===
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "绝区零",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "萝卜子゚",
        "author_id": "0",
        "followers": 0,
        "content": "绝区零这么保值吗就这么点东西挂四百被秒拍了",
        "title": "绝区零这么保值吗",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/187033683",
        "publish_time": "2025-07-31",
        "likes": 387,
        "comments": 155,
        "shares": 0,
        "tags": "绝区零",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "绝区零",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "眼前已非彼时人",
        "author_id": "0",
        "followers": 0,
        "content": "蕾米蕾米埃尔",
        "title": "蕾米蕾米埃尔",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/189060958",
        "publish_time": "2025-08-26",
        "likes": 119,
        "comments": 929,
        "shares": 0,
        "tags": "绝区零",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "绝区零",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "陈子矜",
        "author_id": "0",
        "followers": 0,
        "content": "这个Coser真的哇塞身材是真的顶，妈妈级别的，但是找不到是哪一个了（素材来源于网络）",
        "title": "这个Coser真的哇塞身材是真的顶",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/180162984",
        "publish_time": "2025-04-28",
        "likes": 1872,
        "comments": 11974,
        "shares": 0,
        "tags": "绝区零",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "绝区零",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "玩家100487382",
        "author_id": "100487382",
        "followers": 0,
        "content": "3.1开始玩，我能玩绝区零吗？",
        "title": "3.1开始玩，我能玩绝区零吗？",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/189660097",
        "publish_time": "2025-09-02",
        "likes": 4,
        "comments": 0,
        "shares": 0,
        "tags": "绝区零",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "绝区零",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "流年Jackey",
        "author_id": "0",
        "followers": 0,
        "content": "这个号420值不值",
        "title": "这个号420值不值",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/189432335",
        "publish_time": "2025-08-30",
        "likes": 20,
        "comments": 0,
        "shares": 0,
        "tags": "绝区零",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "绝区零",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "雪恋xl",
        "author_id": "0",
        "followers": 0,
        "content": "排名为香草，喜爱，好感，啥子，无感",
        "title": "角色排名",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/189705128",
        "publish_time": "2025-09-03",
        "likes": 11,
        "comments": 12,
        "shares": 0,
        "tags": "绝区零",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "绝区零",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "思慕洂",
        "author_id": "0",
        "followers": 0,
        "content": "蕾米埃尔官方配队肉腿，黑丝，白丝。原来官方推荐是这个意思啊",
        "title": "蕾米埃尔官方配队",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/187285306",
        "publish_time": "2025-08-03",
        "likes": 102,
        "comments": 884,
        "shares": 0,
        "tags": "绝区零",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "绝区零",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "国家二级心理咨询师",
        "author_id": "0",
        "followers": 0,
        "content": "如果我在乎的从来不是你的牢度呢？虎破王不是区",
        "title": "如果我在乎的从来不是你的牢度呢？",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/189440925",
        "publish_time": "2025-08-30",
        "likes": 68,
        "comments": 98,
        "shares": 0,
        "tags": "绝区零",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "绝区零",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "怎麼回事",
        "author_id": "0",
        "followers": 0,
        "content": "保底必歪啊俩月肝了快700抽就这么对我",
        "title": "保底必歪啊俩月肝了快700抽就这么对我",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/189513734",
        "publish_time": "2025-08-31",
        "likes": 28,
        "comments": 4,
        "shares": 0,
        "tags": "绝区零,抽卡",
    },
    # === 未定事件簿 posts ===
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "未定事件簿",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "Whaoe11k",
        "author_id": "0",
        "followers": 0,
        "content": "这个分析不对吧 其实一直在保底游戏里就是一直在保底 为什么显示这么欧啊 这个分析器的逻辑不太对吧",
        "title": "这个分析不对吧",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/169193308",
        "publish_time": "2025-11-22",
        "likes": 15,
        "comments": 35,
        "shares": 0,
        "tags": "未定事件簿",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "未定事件簿",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "稿诽",
        "author_id": "0",
        "followers": 0,
        "content": "玩未定事件簿一年战绩其实是莫弈激堆来的吧喂！莫弈你这家伙（开个玩笑）",
        "title": "玩未定事件簿一年战绩",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/182415725",
        "publish_time": "2025-05-30",
        "likes": 0,
        "comments": 0,
        "shares": 0,
        "tags": "未定事件簿",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "未定事件簿",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "阿尔缇娜",
        "author_id": "0",
        "followers": 0,
        "content": '米哈游旗下未定事件簿官宣解除与德芙的联动：神仙文案真的强！此前，米哈游旗下乙游未定事件簿宣布与德芙的联动然而在音符平台，德芙官方七夕直播带货却出现了三观相当炸裂的宣传文案，文案内容将"背叛伴侣"的行为包装成甜蜜浪漫，与此前的"纵享丝滑""Do You Love Me"等真挚专一的爱情营销形象完全背道而驰。更炸裂的是官方客服对此回复为"不喜欢可以划走呢"，属于是更加火上浇油。25日官方发布了一则致歉声明，内容完全为甩锅与空话。26日未定事件簿官方wb发布声明，将终止于德芙的合作。',
        "title": "米哈游旗下未定事件簿官宣解除与德芙的联动",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/189135358",
        "publish_time": "2025-08-27",
        "likes": 425,
        "comments": 459,
        "shares": 0,
        "tags": "未定事件簿",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "未定事件簿",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "宇宙串子",
        "author_id": "0",
        "followers": 0,
        "content": '不要再劝mhy女玩家去玩乙游了本人玩过《光与夜之恋》、《未定事件簿》、《时空中的绘旅人》、《恋与深空》四款乙游，最长的玩过两个月，因为歪了三次卡气退游了，不歪的话还能多玩一个月。玩下来我总结了一句话："乙游游戏性几乎为零"。要是对男主兴趣都不大，那乙游根本就不好玩。',
        "title": "不要再劝mhy女玩家去玩乙游了",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/177770365",
        "publish_time": "2025-03-23",
        "likes": 550,
        "comments": 160,
        "shares": 0,
        "tags": "未定事件簿",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "未定事件簿",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "桂秋guiqiu",
        "author_id": "0",
        "followers": 0,
        "content": "米哈游把自己老板卖了666未定制作组太想进步了",
        "title": "米哈游把自己老板卖了666",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/167561328",
        "publish_time": "2025-10-29",
        "likes": 27,
        "comments": 39,
        "shares": 0,
        "tags": "未定事件簿",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "未定事件簿",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "玩家920927",
        "author_id": "920927",
        "followers": 0,
        "content": "？这是什么意思？为什么两个评分不一样？",
        "title": "为什么两个评分不一样？",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/186872984",
        "publish_time": "2025-07-29",
        "likes": 2,
        "comments": 1,
        "shares": 0,
        "tags": "未定事件簿",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "未定事件簿",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "TT",
        "author_id": "0",
        "followers": 0,
        "content": "未定事件簿渠道服能查到抽卡记录吗？",
        "title": "未定事件簿渠道服能查到抽卡记录吗？",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/184640112",
        "publish_time": "2025-06-29",
        "likes": 3,
        "comments": 1,
        "shares": 0,
        "tags": "未定事件簿",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "未定事件簿",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "玩家35976475",
        "author_id": "35976475",
        "followers": 0,
        "content": "终于满级了，可以卸载了竟然用了200多天（零氪）。唯一后悔的是抽夏彦的SSS，以为就他那张卡可以抽，抽到了之后往后滑才发现是4个人各有一张卡…抽SSS的原因它战力最强。",
        "title": "终于满级了，可以卸载了",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/160334963",
        "publish_time": "2025-07-31",
        "likes": 0,
        "comments": 7,
        "shares": 0,
        "tags": "未定事件簿",
    },
    {
        "company_id": "mihoyo",
        "company_name": "米哈游",
        "product_name": "未定事件簿",
        "platform": "xiaoheihe",
        "source_type": "community",
        "author": "20260220",
        "author_id": "0",
        "followers": 0,
        "content": "为什么这里显示不出来卡面图片啊刷新好几次了",
        "title": "为什么这里显示不出来卡面图片啊",
        "url": "https://www.xiaoheihe.cn/app/bbs/link/175936671",
        "publish_time": "2025-02-22",
        "likes": 8,
        "comments": 1,
        "shares": 0,
        "tags": "未定事件簿",
    },
]

if __name__ == "__main__":
    print(f"Importing {len(records)} records from xiaoheihe...")
    stats = import_from_dict(records)
    print(f"\nImport complete!")
    print(f"  Total: {stats['total']}")
    print(f"  Imported: {stats['imported']}")
    print(f"  Skipped (duplicate): {stats['skipped_duplicate']}")
    print(f"  Errors: {stats['errors']}")
    if stats['error_details']:
        print(f"\nError details:")
        for err in stats['error_details']:
            print(f"  - {err}")
